"""
All service methods called by sales.py routes.
"""

from sqlalchemy.orm import Session
from sqlalchemy import func
from datetime import date
from typing import Optional, Tuple, List

from app.models.sale import Sale, SaleItem, Product
from app.models.user import Customer


# =========================
# PRODUCT SEARCH (used by POS)
# =========================

def search_products(db: Session, query: str) -> List[Product]:
    return db.query(Product).filter(
        Product.status == "active",
        (
            Product.name.ilike(f"%{query}%") |
            Product.sku.ilike(f"%{query}%") |
            Product.barcode.ilike(f"%{query}%")
        )
    ).limit(20).all()


def get_product_by_id(db: Session, product_id: int) -> Optional[Product]:
    return db.query(Product).filter(
        Product.product_id == product_id,
        Product.status == "active"
    ).first()


# =========================
# CREATE SALE
# =========================

def create_sale(
    db: Session,
    sale_data,
    user_id: int
) -> Tuple[Optional[Sale], Optional[str]]:
    """
    Creates a Sale and its SaleItem rows. Deducts stock from each product.
    Returns (sale, None) on success, (None, error_message) on failure.
    """
    sale = Sale(
        customer_id=sale_data.customer_id,  #optional
        user_id=user_id,
        receipt_number=sale_data.receipt_number, #generated by caller
        bill_date=date.today(),
        payment_method=sale_data.payment_method,   #cash|upi|credit
        discount_amount=sale_data.discount_amount or 0,  #by caller
        tax_amount=sale_data.tax_amount,   #by caller
        total_amount=sale_data.total_amount,  #by caller
        status="completed"
    )

    db.add(sale)
    db.flush()  # get sale.bill_id without committing

    for item in sale_data.items:
        product = db.query(Product).filter(Product.product_id == item.product_id).first()
        if not product:
            db.rollback()
            return None, f"Product ID {item.product_id} not found"

        if product.stock < item.quantity:
            db.rollback()
            return None, f"Insufficient stock for '{product.name}'"

        # Deduct stock
        product.stock -= item.quantity

        sale_item = SaleItem(
            bill_id=sale.bill_id,
            product_id=item.product_id,
            quantity=item.quantity,
            unit_price=item.unit_price,
            total=round(item.unit_price * item.quantity, 2)
        )
        db.add(sale_item)

    db.commit()
    db.refresh(sale)
    return sale, None


# =========================
# GET SALE
# =========================

def get_sale_by_id(db: Session, bill_id: int) -> Optional[Sale]:
    return db.query(Sale).filter(Sale.bill_id == bill_id).first()


# =========================
# SALES HISTORY
# =========================

def get_sales_history(
    db: Session,
    start_date=None,
    end_date=None,
    payment_method: Optional[str] = None,
    status: Optional[str] = None,
    customer_id: Optional[int] = None,
    skip: int = 0,
    limit: int = 50
) -> Tuple[List[Sale], int]:
    query = db.query(Sale)

    if start_date:
        query = query.filter(Sale.bill_date >= start_date)
    if end_date:
        query = query.filter(Sale.bill_date <= end_date)
    if payment_method:
        query = query.filter(Sale.payment_method == payment_method)
    if status:
        query = query.filter(Sale.status == status)
    if customer_id:
        query = query.filter(Sale.customer_id == customer_id)

    total = query.count()
    sales = query.order_by(Sale.bill_date.desc()).offset(skip).limit(limit).all()
    return sales, total


# =========================
# DAILY SUMMARY
# =========================

def get_daily_summary(db: Session, summary_date: date) -> dict:
    sales = db.query(Sale).filter(
        func.date(Sale.bill_date) == summary_date,
        Sale.status == "completed"
    ).all()

    total_revenue = sum(s.total_amount for s in sales)
    total_discount = sum(s.discount_amount or 0 for s in sales)
    total_tax = sum(s.tax_amount or 0 for s in sales)
    order_count = len(sales)

    cash = sum(s.total_amount for s in sales if s.payment_method == "cash")
    upi = sum(s.total_amount for s in sales if s.payment_method == "upi")
    credit = sum(s.total_amount for s in sales if s.payment_method == "credit")

    return {
        "date": str(summary_date),
        "total_revenue": round(total_revenue, 2),
        "total_discount": round(total_discount, 2),
        "total_tax": round(total_tax, 2),
        "order_count": order_count,
        "average_order_value": round(total_revenue / order_count, 2) if order_count else 0.0,
        "payment_breakdown": {
            "cash": round(cash, 2),
            "upi": round(upi, 2),
            "credit": round(credit, 2)
        }
    }


# =========================
# SALE REVERSAL
# =========================

def reverse_sale(db: Session, bill_id: int) -> Tuple[bool, Optional[str]]:
    """
    Marks the sale as reversed and restores stock for each item.
    Credit balance adjustments are handled by the route layer.
    """
    sale = get_sale_by_id(db, bill_id)
    if not sale:
        return False, "Sale not found"

    if sale.status == "reversed":
        return False, "Sale is already reversed"

    # Restore stock
    items = db.query(SaleItem).filter(SaleItem.bill_id == bill_id).all()
    for item in items:
        product = db.query(Product).filter(Product.product_id == item.product_id).first()
        if product:
            product.stock += item.quantity

    sale.status = "reversed"
    db.commit()
    return True, None